{
    'name': 'Web Trofeos Site',
    'version': '16.0.1.0.0',
    'summary': 'Sitio web de trofeos, medallas y grabado — B2B + B2C',
    'description': 'Sitio web Trofeos con snippets reutilizables, menú dinámico, calculadora de cotización y override visual de website_sale.',
    'category': 'Website',
    'license': 'LGPL-3',
    'author': 'Method',
    'depends': ['website', 'website_sale'],
    'data': [
        'security/ir.model.access.csv',
        'data/website_data.xml',
        'data/sync_categories.xml',
        # layout
        'views/layout/tr_layout.xml',
        'views/layout/tr_header.xml',
        'views/layout/tr_footer.xml',
        # snippets home
        'views/snippets/s_tr_hero.xml',
        'views/snippets/s_tr_badges.xml',
        'views/snippets/s_tr_trust_bar.xml',
        'views/snippets/s_tr_featured_products.xml',
        'views/snippets/s_tr_categories.xml',
        'views/snippets/s_tr_services.xml',
        'views/snippets/s_tr_clients.xml',
        'views/snippets/s_tr_quote_calculator.xml',
        'views/snippets/s_tr_promo_banner.xml',
        'views/snippets/s_tr_bestsellers.xml',
        'views/snippets/s_tr_newsletter.xml',
        'views/snippets/s_tr_map.xml',
        'views/snippets/s_tr_whatsapp.xml',
        # snippets inner pages
        'views/snippets/s_tr_about_hero.xml',
        'views/snippets/s_tr_about_team.xml',
        'views/snippets/s_tr_services_detail.xml',
        'views/snippets/s_tr_b2b_hero.xml',
        'views/snippets/s_tr_b2b_benefits.xml',
        # snippets panel
        'views/snippets/snippets.xml',
        # pages
        'views/pages/home.xml',
        'views/pages/quienes_somos.xml',
        'views/pages/servicios.xml',
        'views/pages/empresas.xml',
        'views/pages/contacto.xml',
        'views/pages/categoria.xml',
    ],
    'assets': {
        'web.assets_frontend': [
            ('prepend', 'web_trofeos/static/src/scss/primary_variables.scss'),
            'web_trofeos/static/src/scss/tr_tokens.scss',
            'web_trofeos/static/src/scss/tr_layout.scss',
            'web_trofeos/static/src/scss/tr_section_common.scss',
            'web_trofeos/static/src/scss/snippets/s_tr_hero.scss',
            'web_trofeos/static/src/scss/snippets/s_tr_badges.scss',
            'web_trofeos/static/src/scss/snippets/s_tr_trust_bar.scss',
            'web_trofeos/static/src/scss/snippets/s_tr_featured_products.scss',
            'web_trofeos/static/src/scss/snippets/s_tr_categories.scss',
            'web_trofeos/static/src/scss/snippets/s_tr_services.scss',
            'web_trofeos/static/src/scss/snippets/s_tr_clients.scss',
            'web_trofeos/static/src/scss/snippets/s_tr_quote_calculator.scss',
            'web_trofeos/static/src/scss/snippets/s_tr_promo_banner.scss',
            'web_trofeos/static/src/scss/snippets/s_tr_bestsellers.scss',
            'web_trofeos/static/src/scss/snippets/s_tr_newsletter.scss',
            'web_trofeos/static/src/scss/snippets/s_tr_map.scss',
            'web_trofeos/static/src/scss/snippets/s_tr_whatsapp.scss',
            'web_trofeos/static/src/scss/snippets/s_tr_about_hero.scss',
            'web_trofeos/static/src/scss/snippets/s_tr_about_team.scss',
            'web_trofeos/static/src/scss/snippets/s_tr_services_detail.scss',
            'web_trofeos/static/src/scss/snippets/s_tr_b2b_hero.scss',
            'web_trofeos/static/src/scss/snippets/s_tr_b2b_benefits.scss',
            'web_trofeos/static/src/scss/tr_contacto.scss',
            'web_trofeos/static/src/scss/tr_website_sale.scss',
            'web_trofeos/static/src/js/snippets/s_tr_hero/000.js',
            'web_trofeos/static/src/js/snippets/s_tr_featured_products/000.js',
            'web_trofeos/static/src/js/snippets/s_tr_quote_calculator/000.js',
            'web_trofeos/static/src/js/snippets/s_tr_whatsapp/000.js',
            'web_trofeos/static/src/js/tr_date_input.js',
        ],
    },
    'installable': True,
    'application': False,
    'auto_install': False,
    'post_init_hook': 'post_init_hook',
    'post_update_hook': 'post_update_hook',
    'uninstall_hook': 'uninstall_hook',
}
